### ISSUE TITLE
Monitor - Archivo ya en uso

### ISSUE THREAD

**Issue by Rayduxz** [LibreDTE/libredte-cliente#4]
Hola, a veces me pasa que cuando uso el cliente en modo monitor el XML aún está siendo generado por el software, por lo que me da el siguiente error:

`Procesando archivo: DTE_33_XXXXXXX_00000XXXX.xml... Traceback (most recent call last):
  File "libredte-cliente/libredte-cliente.py", line 116, in <module>
    sys.exit(main(Cliente, opts, config))
  File "C:\LibreDTE\libredte-cliente\comandos\monitor.py", line 71, in main
    os.rename(f.path, archivo_solicitud)
PermissionError: [WinError 32] El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso: 'C:\\XXX\\DTE_33_XXXXXXX_00000XXXX.xml' -> 'C:\\XXX/DTE_33_XXXXXXX_00000XXXX.xml/solicitud_DTE_33_XXXXXXX_00000XXXX.xml'`

¿Existe la posibilidad de hacer que lo auto reintente para estos casos y que no se cierre el proceso? U otra solución.

Saludos.

**Comment by estebandelaf** [comment]
a) ¿El proceso se queda "pegado" tratando de generar el archivo y ahí ocurre?

b) ¿Ocurre al generar 2 XML? O sea, ¿se genera un XML por tu software y luego generas otro XML antes que termine el anterior? Si es esto ¿los archivos generados por tu software tienen diferentes nombres?

**Comment by estebandelaf** [comment]
Corregido! Actualizar!

https://github.com/LibreDTE/libredte-cliente/commit/8db6106f5ec022c09ddefa4fb4be5587b38d46cb

PD: ¿ustedes tienen cuenta Plus en www.libredte.cl? Si es así, en el futuro abre un ticket en https://libredte.cl/soporte es más rápido que por acá :+1:
